title: Your awesome title
author: Me!
email: test@example.com
description: > # this means to ignore newlines until "baseurl:"
  This is a test to see how to trouble shoot issues on another project.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
